default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

user_config: &user_config
  username: 'postgres'
  password: ''

development:
  <<: *default
  <<: *user_config
  database: shiny_octo_waddle_dev

test:
  <<: *default
  <<: *user_config
  database: shiny_octo_waddle_test

production:
  <<: *default
  <<: *default
  <<: *user_config
  database: shiny_octo_waddle_dev
