# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b0b16bdd6ac9a2bbee476c6650e48cc4dbad65f506be839ab4db816b62a022eca3f915c59056930bbad8022537174cada7136487995690ad1cdaebe5ca487f

test:
  secret_key_base: e846e862e6830392bf601c1c18d4dcb507b205f69a27868cf5f0081164b15272632bdadcc6e2bf5b8a8bd5c71256bf8306bc324ead0321ad9575007afbd3d096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
